# Generated by Django 5.0.6 on 2025-08-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0002_alter_student_department_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='year',
            field=models.CharField(choices=[('first', 'First Year'), ('second', 'Second Year')], default='first', max_length=10),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(),
        ),
    ]
